// Catálogo de Marginalia.
// Datos locales, sin base de datos: este archivo es la única fuente de verdad.
// "cover" apunta a la portada real en Open Library (covers.openlibrary.org, gratuito).
// "nota" es la recomendación manuscrita de la librera que se muestra sobre la portada.
// price y stock no se muestran en la página: son datos para el futuro chatbot.

module.exports = [
  {
    id: 1,
    title: "Dune",
    author: "Frank Herbert",
    genre: "Ciencia ficción",
    price: 18.99,
    year: 1965,
    description: "La casa Atreides acepta el feudo de Arrakis, el planeta desierto donde se extrae la especia que mueve el universo. Política, ecología y destino en la novela que redefinió un género.",
    rating: 4.8,
    stock: 12,
    cover: "https://covers.openlibrary.org/b/id/11481354-L.jpg",
    nota: "el desierto más adictivo que conozco — M."
  },
  {
    id: 2,
    title: "1984",
    author: "George Orwell",
    genre: "Ciencia ficción",
    price: 12.5,
    year: 1949,
    description: "Winston Smith trabaja reescribiendo el pasado para el Partido, hasta que decide empezar a recordar. La distopía sobre la vigilancia y el lenguaje que nunca deja de estar de actualidad.",
    rating: 4.7,
    stock: 7,
    cover: "https://covers.openlibrary.org/b/id/8745958-L.jpg",
    nota: "cada año más actual — M."
  },
  {
    id: 3,
    title: "Fundación",
    author: "Isaac Asimov",
    genre: "Ciencia ficción",
    price: 14.95,
    year: 1951,
    description: "Hari Seldon predice la caída del Imperio Galáctico y funda una enciclopedia para acortar la edad oscura que viene. Matemáticas, imperios y una idea inmensa.",
    rating: 4.6,
    stock: 9,
    cover: "https://covers.openlibrary.org/b/id/12338424-L.jpg"
  },
  {
    id: 4,
    title: "La mano izquierda de la oscuridad",
    author: "Ursula K. Le Guin",
    genre: "Ciencia ficción",
    price: 16.5,
    year: 1969,
    description: "Un enviado humano llega a un planeta helado cuyos habitantes no tienen género fijo. Ciencia ficción como antropología: extraña, elegante y profundamente humana.",
    rating: 4.5,
    stock: 4,
    cover: "https://covers.openlibrary.org/b/id/10618463-L.jpg"
  },
  {
    id: 63,
    title: "Pacto de silencio",
    author: "Andreas Faber-Kaiser",
    genre: "Ensayo",
    price: 16.9,
    year: 1988,
    description: "La investigación que cuestionó la versión oficial del síndrome tóxico de 1981 en España y denunció el cierre en falso del caso. Incómodo entonces, difícil de encontrar hoy.",
    rating: 4.0,
    stock: 4,
    cover: "https://covers.openlibrary.org/b/id/13238188-L.jpg",
    nota: "de los que ya no se reeditan — M."
  },
  {
    id: 5,
    title: "Fahrenheit 451",
    author: "Ray Bradbury",
    genre: "Ciencia ficción",
    price: 13.9,
    year: 1953,
    description: "Montag es bombero: su trabajo es quemar libros. Un día se pregunta por qué. La fábula sobre la lectura y el olvido escrita a máquina en el sótano de una biblioteca.",
    rating: 4.6,
    stock: 0,
    cover: "https://covers.openlibrary.org/b/id/12993656-L.jpg",
    nota: "se nos agota cada vez que alguien quiere prohibir algo — M."
  },
  {
    id: 6,
    title: "Un mundo feliz",
    author: "Aldous Huxley",
    genre: "Ciencia ficción",
    price: 12.95,
    year: 1932,
    description: "Una sociedad perfecta a base de consumo, condicionamiento y una pastilla para cada pena. La otra gran distopía del siglo XX: la que no necesita policía.",
    rating: 4.5,
    stock: 11,
    cover: "https://covers.openlibrary.org/b/id/14022039-L.jpg"
  },
  {
    id: 7,
    title: "Solaris",
    author: "Stanisław Lem",
    genre: "Ciencia ficción",
    price: 15.5,
    year: 1961,
    description: "Un océano pensante devuelve a los científicos sus propios fantasmas. El primer contacto como espejo: quizá lo verdaderamente otro no se pueda entender.",
    rating: 4.5,
    stock: 5,
    cover: "https://covers.openlibrary.org/b/id/12313764-L.jpg"
  },
  {
    id: 8,
    title: "Neuromante",
    author: "William Gibson",
    genre: "Ciencia ficción",
    price: 16.9,
    year: 1984,
    description: "Hackers, inteligencias artificiales y un cielo del color de una tele sin señal. La novela que imaginó el ciberespacio antes de que existiera.",
    rating: 4.4,
    stock: 6,
    cover: "https://covers.openlibrary.org/b/id/283860-L.jpg"
  },
  {
    id: 9,
    title: "El nombre del viento",
    author: "Patrick Rothfuss",
    genre: "Fantasía",
    price: 22.5,
    year: 2007,
    description: "Kvothe cuenta su propia leyenda: la universidad, la magia, la música y la sombra que persigue desde niño. Fantasía moderna con una prosa que se lee cantando.",
    rating: 4.9,
    stock: 3,
    cover: "https://covers.openlibrary.org/b/id/11480483-L.jpg",
    nota: "empieza y despídete del fin de semana — M."
  },
  {
    id: 10,
    title: "El Señor de los Anillos",
    author: "J. R. R. Tolkien",
    genre: "Fantasía",
    price: 29.9,
    year: 1954,
    description: "Un anillo, una comunidad y el largo camino hacia el fuego donde fue forjado. La obra que inventó la fantasía épica tal y como la conocemos.",
    rating: 4.8,
    stock: 6,
    cover: "https://covers.openlibrary.org/b/id/14846613-L.jpg"
  },
  {
    id: 11,
    title: "El Hobbit",
    author: "J. R. R. Tolkien",
    genre: "Fantasía",
    price: 15.95,
    year: 1937,
    description: "Bilbo Bolsón sale de su agujero-hobbit sin pañuelo y vuelve con un tesoro, un anillo y muchas ganas de no volver a salir. La aventura perfecta para empezar.",
    rating: 4.7,
    stock: 14,
    cover: "https://covers.openlibrary.org/b/id/12345036-L.jpg"
  },
  {
    id: 12,
    title: "Un mago de Terramar",
    author: "Ursula K. Le Guin",
    genre: "Fantasía",
    price: 14.5,
    year: 1968,
    description: "El joven Ged aprende que la magia consiste en conocer el verdadero nombre de las cosas, y que la sombra que le persigue tiene el suyo. Sabia, breve, enorme.",
    rating: 4.4,
    stock: 6,
    cover: "https://covers.openlibrary.org/b/id/13617691-L.jpg"
  },
  {
    id: 13,
    title: "La historia interminable",
    author: "Michael Ende",
    genre: "Fantasía",
    price: 16.95,
    year: 1979,
    description: "Bastian roba un libro y descubre que Fantasia se muere porque los humanos han dejado de imaginar. Un libro sobre leer libros, para todas las edades.",
    rating: 4.6,
    stock: 8,
    cover: "https://covers.openlibrary.org/b/id/10448326-L.jpg"
  },
  {
    id: 14,
    title: "Don Quijote de la Mancha",
    author: "Miguel de Cervantes",
    genre: "Clásicos",
    price: 24.5,
    year: 1605,
    description: "Un hidalgo lee demasiados libros de caballerías y decide salir a deshacer entuertos. La primera novela moderna y, cuatro siglos después, todavía la más libre.",
    rating: 4.6,
    stock: 5,
    cover: "https://covers.openlibrary.org/b/id/13478610-L.jpg"
  },
  {
    id: 15,
    title: "Cien años de soledad",
    author: "Gabriel García Márquez",
    genre: "Clásicos",
    price: 19.95,
    year: 1967,
    description: "Siete generaciones de los Buendía en Macondo, donde llueve cuatro años y los muertos no siempre se van. El realismo mágico en su forma más pura.",
    rating: 4.8,
    stock: 10,
    cover: "https://covers.openlibrary.org/b/id/12627383-L.jpg",
    nota: "se lee como llueve en Macondo: sin parar — M."
  },
  {
    id: 16,
    title: "Orgullo y prejuicio",
    author: "Jane Austen",
    genre: "Clásicos",
    price: 11.95,
    year: 1813,
    description: "Elizabeth Bennet y el señor Darcy se caen mal con una precisión encantadora. Ironía fina, diálogos perfectos y el malentendido más famoso de la literatura.",
    rating: 4.6,
    stock: 13,
    cover: "https://covers.openlibrary.org/b/id/13574150-L.jpg"
  },
  {
    id: 17,
    title: "Crimen y castigo",
    author: "Fiódor Dostoievski",
    genre: "Clásicos",
    price: 17.5,
    year: 1866,
    description: "Raskólnikov comete un crimen para demostrar una teoría y descubre que la conciencia no lee teorías. El termómetro moral de la novela rusa.",
    rating: 4.7,
    stock: 6,
    cover: "https://covers.openlibrary.org/b/id/12328823-L.jpg"
  },
  {
    id: 18,
    title: "Rebelión en la granja",
    author: "George Orwell",
    genre: "Clásicos",
    price: 11.5,
    year: 1945,
    description: "Los animales expulsan al granjero para fundar una sociedad de iguales. Poco a poco, algunos se vuelven más iguales que otros. La fábula política definitiva.",
    rating: 4.6,
    stock: 9,
    cover: "https://covers.openlibrary.org/b/id/13712713-L.jpg"
  },
  {
    id: 19,
    title: "La condición humana",
    author: "André Malraux",
    genre: "Clásicos",
    price: 16.95,
    year: 1933,
    description: "Shanghái, 1927: un puñado de revolucionarios ante una insurrección condenada. Malraux convierte la política en tragedia y la acción en pregunta filosófica.",
    rating: 4.4,
    stock: 5,
    cover: "https://covers.openlibrary.org/b/id/14921675-L.jpg"
  },
  {
    id: 20,
    title: "Rayuela",
    author: "Julio Cortázar",
    genre: "Clásicos",
    price: 18.95,
    year: 1963,
    description: "Una novela que puede leerse en orden o a saltos, como se vive. París, Buenos Aires, la Maga y el arte de encontrarse sin buscarse.",
    rating: 4.5,
    stock: 7,
    cover: "https://covers.openlibrary.org/b/id/1047466-L.jpg"
  },
  {
    id: 21,
    title: "La metamorfosis",
    author: "Franz Kafka",
    genre: "Clásicos",
    price: 9.99,
    year: 1915,
    description: "Gregor Samsa despierta convertido en un insecto monstruoso, y su familia despierta convertida en otra cosa. Nadie ha contado mejor la extrañeza de existir.",
    rating: 4.6,
    stock: 16,
    cover: "https://covers.openlibrary.org/b/id/14073660-L.jpg"
  },
  {
    id: 22,
    title: "El extranjero",
    author: "Albert Camus",
    genre: "Clásicos",
    price: 11.95,
    year: 1942,
    description: "Meursault no llora en el entierro de su madre, y el mundo no se lo perdona. La novela del absurdo, escrita con sol y con cuchillo.",
    rating: 4.6,
    stock: 10,
    cover: "https://covers.openlibrary.org/b/id/15070895-L.jpg"
  },
  {
    id: 23,
    title: "Ficciones",
    author: "Jorge Luis Borges",
    genre: "Clásicos",
    price: 13.5,
    year: 1944,
    description: "Bibliotecas infinitas, laberintos, un mapa del tamaño del mundo. Diecisiete cuentos que caben en un bolsillo y contienen el universo.",
    rating: 4.8,
    stock: 9,
    cover: "https://covers.openlibrary.org/b/id/10832290-L.jpg"
  },
  {
    id: 24,
    title: "El Principito",
    author: "Antoine de Saint-Exupéry",
    genre: "Infantil",
    price: 9.95,
    year: 1943,
    description: "Un aviador averiado en el desierto conoce a un niño que viene de un asteroide con tres volcanes y una rosa. El libro pequeño que hace las preguntas grandes.",
    rating: 4.8,
    stock: 20,
    cover: "https://covers.openlibrary.org/b/id/13499066-L.jpg",
    nota: "para llorar a los 8 y entenderlo a los 30 — M."
  },
  {
    id: 25,
    title: "Momo",
    author: "Michael Ende",
    genre: "Infantil",
    price: 14.5,
    year: 1973,
    description: "Los hombres grises roban el tiempo de la gente y solo una niña que sabe escuchar puede devolverlo. Un cuento sobre la prisa, escrito para todas las edades.",
    rating: 4.7,
    stock: 12,
    cover: "https://covers.openlibrary.org/b/id/8574580-L.jpg"
  },
  {
    id: 28,
    title: "La sombra del viento",
    author: "Carlos Ruiz Zafón",
    genre: "Clásicos",
    price: 19.5,
    year: 2001,
    description: "En el Cementerio de los Libros Olvidados, Daniel adopta un libro y alguien empieza a quemar todos los ejemplares de su autor. Barcelona, niebla y libros dentro de libros.",
    rating: 4.6,
    stock: 2,
    cover: "https://covers.openlibrary.org/b/id/10107644-L.jpg",
    nota: "para quien ama los libros que hablan de libros — M."
  },
  {
    id: 32,
    title: "Frankenstein",
    author: "Mary Shelley",
    genre: "Clásicos",
    price: 13.5,
    year: 1818,
    description: "Un científico da vida a una criatura y huye de ella. Escrita a los dieciocho años, es novela gótica y, a la vez, la primera gran pregunta sobre la responsabilidad de crear.",
    rating: 4.6,
    stock: 9,
    cover: "https://covers.openlibrary.org/b/id/12356249-L.jpg"
  },
  {
    id: 33,
    title: "Campos de Castilla",
    author: "Antonio Machado",
    genre: "Poesía",
    price: 10.95,
    year: 1912,
    description: "Los caminos, los olmos secos y la España que duele y espera. Machado en su voz más honda: la que se aprende de memoria sin querer.",
    rating: 4.4,
    stock: 9,
    cover: "https://covers.openlibrary.org/b/id/904033-L.jpg"
  },
  {
    id: 34,
    title: "Veinte poemas de amor y una canción desesperada",
    author: "Pablo Neruda",
    genre: "Poesía",
    price: 9.99,
    year: 1924,
    description: "El libro de amor más leído en lengua española, escrito a los diecinueve años. Puedo escribir los versos más tristes esta noche… y los demás también.",
    rating: 4.5,
    stock: 12,
    cover: "https://covers.openlibrary.org/b/id/747596-L.jpg"
  },
  {
    id: 35,
    title: "Rimas y leyendas",
    author: "Gustavo Adolfo Bécquer",
    genre: "Poesía",
    price: 9.99,
    year: 1871,
    description: "Golondrinas que no volverán y suspiros que son aire. El romanticismo español en su versión más pura y más citada.",
    rating: 4.4,
    stock: 10,
    cover: "https://covers.openlibrary.org/b/id/2271282-L.jpg"
  },
  {
    id: 36,
    title: "Homenaje a Cataluña",
    author: "George Orwell",
    genre: "Ensayo",
    price: 15.9,
    year: 1938,
    description: "Orwell cuenta la guerra que vivió como miliciano en España: el frente, el frío y la batalla por contar la verdad. Periodismo en primera persona.",
    rating: 4.5,
    stock: 6,
    cover: "https://covers.openlibrary.org/b/id/7282177-L.jpg"
  },
  {
    id: 37,
    title: "Recuerdos del futuro",
    author: "Erich von Däniken",
    genre: "Ensayo",
    price: 13.95,
    year: 1968,
    description: "¿Y si los dioses de la antigüedad hubieran sido astronautas? La provocación que fundó un género entero de misterios. Para leer con asombro… y con espíritu crítico.",
    rating: 3.9,
    stock: 0,
    cover: "https://covers.openlibrary.org/b/id/270259-L.jpg",
    nota: "léase con una ceja levantada — M."
  },
  {
    id: 38,
    title: "Cosmos",
    author: "Carl Sagan",
    genre: "Ensayo",
    price: 21.9,
    year: 1980,
    description: "Un viaje por el universo y por la historia de cómo aprendimos a mirarlo. Ciencia contada con la voz de alguien que nunca perdió el asombro.",
    rating: 4.8,
    stock: 7,
    cover: "https://covers.openlibrary.org/b/id/8283901-L.jpg"
  },
  {
    id: 39,
    title: "El hombre en busca de sentido",
    author: "Viktor Frankl",
    genre: "Ensayo",
    price: 12.9,
    year: 1946,
    description: "Un psiquiatra superviviente de los campos escribe sobre lo único que no pudieron quitarle: la libertad de elegir la propia actitud. Breve y definitivo.",
    rating: 4.8,
    stock: 14,
    cover: "https://covers.openlibrary.org/b/id/11203708-L.jpg"
  },
  {
    id: 40,
    title: "Una habitación propia",
    author: "Virginia Woolf",
    genre: "Ensayo",
    price: 11.9,
    year: 1929,
    description: "Woolf responde a una pregunta simple —¿por qué hay tan pocas escritoras?— con el ensayo más elegante y afilado del siglo.",
    rating: 4.6,
    stock: 8,
    cover: "https://covers.openlibrary.org/b/id/6368401-L.jpg"
  },
  {
    id: 41,
    title: "Meditaciones",
    author: "Marco Aurelio",
    genre: "Ensayo",
    price: 10.95,
    year: 180,
    description: "Las notas privadas de un emperador que se recordaba a sí mismo cómo ser persona. Diecinueve siglos después, siguen funcionando.",
    rating: 4.7,
    stock: 11,
    cover: "https://covers.openlibrary.org/b/id/10469464-L.jpg",
    nota: "un emperador con mejores hábitos que tú y que yo — M."
  },
  {
    id: 42,
    title: "El mito de Sísifo",
    author: "Albert Camus",
    genre: "Ensayo",
    price: 12.5,
    year: 1942,
    description: "¿Vale la pena vivir una vida sin sentido? Camus empieza por la pregunta más seria de todas y termina imaginando a Sísifo feliz.",
    rating: 4.5,
    stock: 6,
    cover: "https://covers.openlibrary.org/b/id/15249764-L.jpg"
  },
  {
    id: 43,
    title: "El shock del futuro",
    author: "Alvin Toffler",
    genre: "Ensayo",
    price: 14.95,
    year: 1970,
    description: "Demasiado cambio en demasiado poco tiempo: en 1970 Toffler ya describía el vértigo de vivir en aceleración permanente. El ensayo que le puso nombre a nuestra época.",
    rating: 4.2,
    stock: 6,
    cover: "https://covers.openlibrary.org/b/id/368968-L.jpg",
    nota: "escrito en 1970, describe tu móvil — M."
  },
  {
    id: 44,
    title: "Yo, robot",
    author: "Isaac Asimov",
    genre: "Ciencia ficción",
    price: 13.95,
    year: 1950,
    description: "Nueve relatos y tres leyes de la robótica que definieron cómo pensamos en las máquinas. Susan Calvin, robopsicóloga, examina robots que fallan de maneras muy humanas.",
    rating: 4.6,
    stock: 10,
    cover: "https://covers.openlibrary.org/b/id/12385229-L.jpg",
    nota: "para leer antes de programar un chatbot — M."
  },
  {
    id: 45,
    title: "El fin de la eternidad",
    author: "Isaac Asimov",
    genre: "Ciencia ficción",
    price: 14.5,
    year: 1955,
    description: "Una organización fuera del tiempo corrige la historia siglo a siglo, hasta que un técnico se enamora y empieza a cuestionarlo todo. Para muchos, el mejor Asimov en una sola novela.",
    rating: 4.5,
    stock: 7,
    cover: "https://covers.openlibrary.org/b/id/6622699-L.jpg"
  },
  {
    id: 46,
    title: "Regreso a las estrellas",
    author: "Erich von Däniken",
    genre: "Ensayo",
    price: 13.5,
    year: 1969,
    description: "Segunda entrega de la teoría de los antiguos astronautas: más templos, más mapas imposibles y más preguntas incómodas. Mejor leerlo discutiendo.",
    rating: 3.8,
    stock: 5,
    cover: "https://covers.openlibrary.org/b/id/14970268-L.jpg"
  },
  {
    id: 47,
    title: "El oro de los dioses",
    author: "Erich von Däniken",
    genre: "Ensayo",
    price: 13.9,
    year: 1972,
    description: "Túneles bajo Ecuador, bibliotecas metálicas y visitantes de otros mundos. La arqueología ortodoxa dice que no; von Däniken dice: mira.",
    rating: 3.7,
    stock: 4,
    cover: "https://covers.openlibrary.org/b/id/8620774-L.jpg"
  },
  {
    id: 48,
    title: "La esperanza",
    author: "André Malraux",
    genre: "Clásicos",
    price: 15.9,
    year: 1937,
    description: "La guerra civil española contada desde dentro por quien voló en ella: brigadas, aviones viejos y la fe en que la dignidad puede organizarse.",
    rating: 4.3,
    stock: 5,
    cover: "https://covers.openlibrary.org/b/id/15011832-L.jpg"
  },
  {
    id: 49,
    title: "Introducción a la genética",
    author: "A. M. Winchester",
    genre: "Ciencia",
    price: 16.5,
    year: 1958,
    description: "El manual clásico con el que generaciones enteras aprendieron qué es un gen, cómo se hereda un rasgo y por qué te pareces a tu abuela.",
    rating: 4.1,
    stock: 6,
    cover: "https://covers.openlibrary.org/b/id/9654206-L.jpg"
  },
  {
    id: 50,
    title: "Changó, el gran putas",
    author: "Manuel Zapata Olivella",
    genre: "Historia",
    price: 18.9,
    year: 1983,
    description: "La epopeya de la diáspora africana en América: orishas, barcos negreros y cinco siglos de rebelión contados con tambor. Una cumbre de la literatura colombiana.",
    rating: 4.7,
    stock: 5,
    cover: "https://covers.openlibrary.org/b/id/14403536-L.jpg",
    nota: "la historia que no nos contaron en clase — M."
  },
  {
    id: 51,
    title: "La rebelión de las ratas",
    author: "Fernando Soto Aparicio",
    genre: "Clásicos",
    price: 11.9,
    year: 1962,
    description: "Un pueblo minero devorado por una compañía extranjera y un hombre que decide no agachar más la cabeza. Novela social colombiana de las que dejan marca.",
    rating: 4.4,
    stock: 8,
    cover: "https://covers.openlibrary.org/b/id/8078371-L.jpg"
  },
  {
    id: 52,
    title: "Matar a un ruiseñor",
    author: "Harper Lee",
    genre: "Clásicos",
    price: 13.9,
    year: 1960,
    description: "Scout, su padre Atticus y un juicio injusto en el sur de Estados Unidos. Sobre el valor de defender lo correcto cuando todo el pueblo mira hacia otro lado.",
    rating: 4.8,
    stock: 11,
    cover: "https://covers.openlibrary.org/b/id/14351077-L.jpg"
  },
  {
    id: 53,
    title: "La guerra de las salamandras",
    author: "Karel Čapek",
    genre: "Ciencia ficción",
    price: 14.5,
    year: 1936,
    description: "La humanidad descubre salamandras inteligentes, las explota… y ellas aprenden rápido. Sátira profética escrita justo antes de la guerra que anunciaba.",
    rating: 4.5,
    stock: 6,
    cover: "https://covers.openlibrary.org/b/id/4113422-L.jpg"
  },
  {
    id: 54,
    title: "Sapiens: De animales a dioses",
    author: "Yuval Noah Harari",
    genre: "Historia",
    price: 21.9,
    year: 2011,
    description: "Cien mil años de Homo sapiens en un solo relato: fuego, mitos, dinero e imperios. El libro que puso a medio planeta a leer historia.",
    rating: 4.6,
    stock: 12,
    cover: "https://covers.openlibrary.org/b/id/8634250-L.jpg",
    nota: "todos tus antepasados están aquí — M."
  },
  {
    id: 55,
    title: "El origen de las especies",
    author: "Charles Darwin",
    genre: "Ciencia",
    price: 14.9,
    year: 1859,
    description: "El libro que cambió lo que significa estar vivo: la evolución por selección natural explicada con paciencia de naturalista.",
    rating: 4.6,
    stock: 7,
    cover: "https://covers.openlibrary.org/b/id/7153600-L.jpg"
  },
  {
    id: 56,
    title: "Los versos satánicos",
    author: "Salman Rushdie",
    genre: "Clásicos",
    price: 19.5,
    year: 1988,
    description: "Dos actores indios caen de un avión y sobreviven a todo, menos al escándalo. Prohibido en una docena de países y su autor perseguido: pocas novelas han pagado tan caro ser leídas.",
    rating: 4.2,
    stock: 4,
    cover: "https://covers.openlibrary.org/b/id/8312209-L.jpg"
  },
  {
    id: 58,
    title: "Archipiélago Gulag",
    author: "Aleksandr Solzhenitsyn",
    genre: "Historia",
    price: 24.9,
    year: 1973,
    description: "La investigación clandestina sobre los campos soviéticos que su propio país prohibió y persiguió. Escrita a escondidas y sacada del país en microfilm.",
    rating: 4.7,
    stock: 3,
    cover: "https://covers.openlibrary.org/b/id/14974821-L.jpg"
  },
  {
    id: 59,
    title: "Mundos en colisión",
    author: "Immanuel Velikovsky",
    genre: "Ensayo",
    price: 14.5,
    year: 1950,
    description: "Venus como cometa, plagas bíblicas y catástrofes planetarias. La comunidad científica lo condenó con tanta furia que el escándalo tiene nombre propio: el «caso Velikovsky».",
    rating: 3.6,
    stock: 4,
    cover: "https://covers.openlibrary.org/b/id/7128871-L.jpg"
  },
  {
    id: 60,
    title: "El retorno de los brujos",
    author: "Louis Pauwels y Jacques Bergier",
    genre: "Ensayo",
    price: 15.9,
    year: 1960,
    description: "Alquimia, civilizaciones perdidas y ciencia heterodoxa: el libro que inventó el «realismo fantástico» y que la academia desdeñó mientras vendía millones.",
    rating: 3.9,
    stock: 5,
    cover: "https://covers.openlibrary.org/b/id/9541137-L.jpg",
    nota: "la madre de todos los misterios — M."
  },
  {
    id: 61,
    title: "Las enseñanzas de Don Juan",
    author: "Carlos Castaneda",
    genre: "Ensayo",
    price: 14.9,
    year: 1968,
    description: "Un estudiante de antropología y un brujo yaqui en el desierto de Sonora. Celebrado como etnografía y desacreditado después como invención: nadie sabe aún cuánto es verdad.",
    rating: 3.8,
    stock: 6,
    cover: "https://covers.openlibrary.org/b/id/406890-L.jpg"
  },
  {
    id: 64,
    title: "Tecnofeudalismo",
    author: "Yanis Varoufakis",
    genre: "Ensayo",
    price: 19.9,
    year: 2023,
    description: "¿Y si el capitalismo ya hubiera muerto y lo hubieran sustituido los feudos de las plataformas? El exministro griego contra los nuevos señores del algoritmo.",
    rating: 4.3,
    stock: 8,
    cover: "https://covers.openlibrary.org/b/id/15122209-L.jpg"
  },
  {
    id: 65,
    title: "La espada de la vida",
    author: "Alfonso Araujo y Víctor Ruy Quijano",
    genre: "Ensayo",
    price: 14.5,
    year: 2005,
    description: "Treinta y siete aforismos de un texto marcial chino que, según sus autores, permaneció oculto durante siglos e inspiró El Kybalión. Sabiduría heterodoxa comentada frase a frase.",
    rating: 3.9,
    stock: 3
  },
  {
    id: 66,
    title: "Vigilancia permanente",
    author: "Edward Snowden",
    genre: "Ensayo",
    price: 18.9,
    year: 2019,
    description: "El técnico que reveló la vigilancia masiva global cuenta cómo y por qué lo hizo. El gobierno de Estados Unidos demandó el libro el mismo día que salió a la venta.",
    rating: 4.5,
    stock: 9,
    nota: "léalo y tape la webcam — M.",
    cover: "https://covers.openlibrary.org/b/id/8751316-L.jpg"
  },
  {
    id: 67,
    title: "Operación Masacre",
    author: "Rodolfo Walsh",
    genre: "Historia",
    price: 14.9,
    year: 1957,
    description: "Walsh investigó los fusilamientos clandestinos de José León Suárez cuando ninguna editorial se atrevía a tocarlos, y fundó sin querer el periodismo narrativo. Veinte años después, otra dictadura lo desapareció a él.",
    rating: 4.7,
    stock: 6,
    cover: "https://covers.openlibrary.org/b/id/5407660-L.jpg"
  },
  {
    id: 68,
    title: "Confesiones de un gángster económico",
    author: "John Perkins",
    genre: "Ensayo",
    price: 17.5,
    year: 2004,
    description: "Un exconsultor cuenta cómo se endeuda y se doblega a países enteros desde los despachos. Desacreditado por unos, incómodamente verosímil para otros.",
    rating: 4.1,
    stock: 7,
    cover: "https://covers.openlibrary.org/b/id/13977093-L.jpg"
  },
  {
    id: 69,
    title: "Diálogo sobre los dos máximos sistemas del mundo",
    author: "Galileo Galilei",
    genre: "Ciencia",
    price: 19.9,
    year: 1632,
    description: "El diálogo que defendía que la Tierra se mueve. La Inquisición lo prohibió, juzgó a su autor y lo mantuvo dos siglos en el Índice de libros prohibidos. Galileo acabó recluido; el libro acabó teniendo razón.",
    rating: 4.4,
    stock: 3,
    cover: "https://covers.openlibrary.org/b/id/230388-L.jpg",
    nota: "la Tierra se mueve, digan lo que digan — M."
  },
  {
    id: 70,
    title: "El príncipe",
    author: "Nicolás Maquiavelo",
    genre: "Ensayo",
    price: 10.5,
    year: 1532,
    description: "El manual del poder sin maquillaje. La Iglesia lo metió en el Índice de libros prohibidos y los príncipes lo condenaban en público mientras lo estudiaban en privado.",
    rating: 4.5,
    stock: 14,
    cover: "https://covers.openlibrary.org/b/id/12726168-L.jpg"
  },
  {
    id: 71,
    title: "Las venas abiertas de América Latina",
    author: "Eduardo Galeano",
    genre: "Historia",
    price: 17.9,
    year: 1971,
    description: "Cinco siglos de saqueo del continente contados con datos y rabia serena. Las dictaduras de Uruguay, Argentina y Chile lo prohibieron a la vez: pocas reseñas mejores.",
    rating: 4.6,
    stock: 8,
    cover: "https://covers.openlibrary.org/b/id/5416334-L.jpg",
    nota: "prohibido por tres dictaduras a la vez — M."
  },
  {
    id: 72,
    title: "Doctor Zhivago",
    author: "Borís Pasternak",
    genre: "Clásicos",
    price: 16.9,
    year: 1957,
    description: "La novela que la URSS prohibió y la CIA imprimió en ruso para colarla de vuelta al país. A Pasternak le dieron el Nobel y su gobierno le obligó a rechazarlo.",
    rating: 4.5,
    stock: 6,
    cover: "https://covers.openlibrary.org/b/id/12713393-L.jpg"
  },
  {
    id: 73,
    title: "Los papeles del Pentágono",
    author: "Neil Sheehan y The New York Times",
    genre: "Historia",
    price: 22.9,
    year: 1971,
    description: "Los documentos secretos que demostraban que el gobierno de Estados Unidos mentía sobre Vietnam. La Casa Blanca llegó a la Corte Suprema para impedir su publicación — y perdió.",
    rating: 4.4,
    stock: 2,
    cover: "https://covers.openlibrary.org/b/id/11700627-L.jpg"
  }
];
